type Brand = "Voltas" | "Carrier" | "Daikin";

interface ServiceInfoByBrand {
  Voltas: VoltasServiceInfo;
  Carrier: CMIServiceInfo;
  Daikin: DaikinServiceInfo;
}

type ServiceInfoData =
  | { brand: "Voltas"; data: VoltasServiceInfo }
  | { brand: "Carrier"; data: CMIServiceInfo }
  | { brand: "Daikin"; data: DaikinServiceInfo }
  | { brand: "DaikinV2"; data: DaikinCaseInfo };

type DaikinCaseInfo = {
  ticketId: string;
  caseType: string;
  customerName: string;
  customerAddress: string;
  customerMobile: string;
  unitStatus: string;
};

interface DaikinServiceInfo {
  AMC: string;
  "AMC Approved": string;
  "AMC Contract": string;
  "ASP/SSD": string;
  "Actual Warranty": string;
  Address: string;
  "Appointment End Date": string;
  "Appointment Start Date": string;
  "Appointment Start Date Time": string;
  "Approval Status": string;
  "Area/Locality": string;
  "Assigned To": string;
  "Audit Status": string;
  "AutoAllocation Area/Locality": string;
  "AutoAllocation Postal Code": string;
  "Branch Value": string;
  "Building/Floor/Room": string;
  "Call Center Scheduler": string;
  "Call Type": string;
  "Caller Details": string;
  Category: string;
  "Cause Category": string;
  City: string;
  "Closed By": string;
  "Completion Date": string;
  "Completion Due": string;
  Contract: string;
  "Contract End Date": string;
  "Contract Line Item Number": string;
  "Contract Start Date": string;
  Country: string;
  "Country Region": string;
  Coverage: string;
  "Created By": string;
  "Created On": string;
  Customer: string;
  "Customer Contactable": string;
  "Customer FeedBack": string;
  "Customer ID": string;
  "Customer Response Due Time": string;
  "Customer Response On Cancellation": string;
  "Customer WCC": string;
  "Customer City": string;
  "Customer Comments": string;
  "Customer Pincode": string;
  DND: string;
  "Data Creation Date": string;
  "Data Creation Time": string;
  "Dealer Location": string;
  "Dlr ID": string;
  "Dlr Vndr": string;
  Email: string;
  "EW End Date": string;
  "EW Plan Type": string;
  "EW Start Date": string;
  "Escalated On": string;
  "Free Installation Ticket ID": string;
  "Free Installation Approval": string;
  "House Number": string;
  HouseID: string;
  "Incoming Calls": string;
  "Initial Review Due": string;
  "Installation ID": string;
  "Installed Base": string;
  "Installed Base Type": string;
  "Installed Location": string;
  Landmark: string;
  Mobile: string;
  "Next Response Due": string;
  "Out Of Warranty": string;
  "Outgoing Calls": string;
  "Partner Type": string;
  Phone: string;
  "Postal Code": string;
  "Previous Sub Status": string;
  Priority: string;
  Product: string;
  "Product Category": string;
  "Product ID": string;
  "Product Replacement": string;
  "Product Title": string;
  "Product Type": string;
  "Quality Of Service": string;
  "Reason For Change": string;
  "Reason For Escalation": string;
  "Reason For ReAppointment": string;
  "Reason For Reallocation": string;
  "Resolution Category": string;
  "Resolution Due": string;
  "Resolved On": string;
  "SO Fail Reason": string;
  "Serial ID": string;
  "Service Technician": string;
  "Service Technician ID": string;
  "Ship To": string;
  "Source Of Call": string;
  "Spare Parts Consumed": string;
  State: string;
  Status: string;
  Street: string;
  "Sub Cause Category": string;
  "Sub Status": string;
  "Sub Ticket": string;
  "Sub Type": string;
  Subject: string;
  "Survey Start Date": string;
  Team: string;
  "Ticket Created Last Month": string;
  "Ticket Created Last Week": string;
  "Ticket ID": string;
  "Ticket Count": string;
  "Time With Agent": string;
  "Time With Customer": string;
  Type: string;
  "WCC SMS Retrigger": string;
  Warranty: string;
  "Warranty From": string;
  "Warranty To": string;
  "Work Description": string;
  "Work Progress": string;
  "Down Time": string;
  "Down Time Day": string;
  "Response Time": string;
  "Warranty Status Of IBase": string;
}

interface CMIServiceInfo {
  "Allocated Eng.[Code]": string;
  "Call Completion Date": string;
  "Call Logged By": string;
  "Call Logged Date": string;
  "Call Source": string;
  "Call Status": string;
  Company: string;
  "Coverage as per Customer": string;
  "Customer Classification": string;
  "Customer Name": string;
  "Customer RelationShip ID": string;
  "Customer Relationship with CMI": string;
  "Customer Remarks": string;
  "Document Upload": string;
  "Engineer Allocation Remarks": string;
  "FSR Scanned Copy": string;
  "Incident No.": string;
  "Installation Address": string;
  "Is Repeat Repair": string;
  "Last Modified At": string;
  "Last Modified By": string;
  Model: string;
  "Overall rating": string;
  "Pending Reason": string;
  "Pre-Approved Amount": string;
  "Pre-Approved Item Cost": string;
  "Pre-Approved Labor Cost": string;
  "Previous Call No": string;
  "Product Category": string;
  "Product Coverage": string;
  "Re-Seller Name": string;
  "Reason for Std TAT violation": string;
  "Scheduled At": string;
  "Serial No.": string;
  "Service Completion Date ": string;
  "Service Coverage": string;
  "Service Location": string;
  "Service Outcome": string;
  "Service Outcome Remarks": string;
  "Service Requester Mobile No": string;
  "Service Status": string;
  "Service Sub Type": string;
  "Service Type": string;
  "Std TAT": string;
  "Tech Rating": string;
  "Transaction No.": string;
  "Registered Phone": string;
  "Alternate Phone": string;
}

interface VoltasServiceInfo {
  Account: string;
  "Account Type": string;
  "Activation Key": string;
  Agreement: string;
  "Alternate Phone": string;
  Appointment: string;
  Area: string;
  Assigned: string;
  Billable: string;
  Branch: string;
  "Brand Identifier": string;
  Building: string;
  "CSA Area Type": string;
  "Call Type": string;
  "Cancel Reason": string;
  Capacity: string;
  Category: string;
  City: string;
  "Closure Code": string;
  Contact: string;
  "Contact #": string;
  "Coupon Code": string;
  "Customer Mood": string;
  "Date Closed": string;
  District: string;
  "Email Address": string;
  Escalation: string;
  "External SR #": string;
  "External Ticket ID": string;
  "FSC Code": string;
  "Fee Amount": string;
  Group: string;
  "House #": string;
  "Installed By": string;
  "Invalid Code Remarks": string;
  "Key Account (P)": string;
  "Key Account (S)": string;
  Landmark: string;
  Model: string;
  "Model #": string;
  "Open Date": string;
  Pincode: string;
  "Program #": string;
  "Promo Code": string;
  "Purchase Date": string;
  "Purchased From": string;
  "Purchased From Code": string;
  "Purchased From Type": string;
  "Registered By": string;
  "Registered Phone": string;
  "Reopen Reason": string;
  Road: string;
  "SR #": string;
  "SR Value": string;
  "Serial #": string;
  "Serial #(Split)": string;
  "Service By": string;
  "Service Phone": string;
  Severity: string;
  State: string;
  Status: string;
  "Status Date": string;
  "Sub Area": string;
  Substatus: string;
  Symptom: string;
  "TCR #": string;
  "TCR Date": string;
  Technician: string;
  "Technician Phone": string;
  "Threshold Value": string;
  "Total Ereceipt": string;
  "Total Payment": string;
  "Total Value": string;
  Type: string;
  "Unit Status": string;
}
