export const ProductMap = {
    "AIR PURIFIER FLOOR STANDING [FS]": "Air Purifier",
    "AIR PURIFIER TABLE TOP [TT]": "Air Purifier",
    "CASSATE R22 [CS]": "Cassette AC",
    "CASSETTE INVERTER [CSINVERTER]": "Cassette AC",
    "CASSETTE INVERTER – R32 [CSINVR32]": "Cassette AC",
    "CASSETTE R 32 [CSFIXR32]": "Cassette AC",
    "CASSETTE R410A [CS410]": "Cassette AC",
    "CONVECTION MWO [CONMWO]": "Microwave Oven",
    "DISH WASHER COUNTER TOP [CT]": "Dish Washer",
    "DISH WASHER FLOOR STANDING [DWFS]": "Dish Washer",
    "DMS CAT [DMSC]": "DMS CAT",
    "DUCTABLE [DUCT]": "Ductable AC",
    "DUCT INVETER [DUCTINV]": "Ductable AC",
    "FLOOR STANDING R-22 [TOWER]": "Tower AC",
    "FLOOR STANDING R32 [TOWER32]": "Tower AC",
    "FLOOR STANDING R410A [TOWER410]": "Tower AC",
    "FRONT LOADING [WM03]": "Washing Machine",
    "FULLY AUTOMATIC TOP LOADING [WM02]": "Washing Machine",
    "GRILL MWO [GRILL]": "Microwave Oven",
    "HI WALL [HIWALL]": "AC",
    "HI WALL M [HIWALLM]": "AC",
    "HI WALL SPLIT AIRCONDITIONER [DFS]": "AC",
    "HI WALL SPLIT INVERTER AIRCONDITIONER [DFSI]": "AC",
    "PORTABLE AC R410A [PORT]": "Portable AC",
    "REF FROST FREE [REFFF]": "Refrigerator",
    "REF MULTI DOOR [REFMLD]": "Refrigerator",
    "REF Side by Side [REFSBS]": "Refrigerator",
    "ROTISSERRIE [ROTMWO]": "Microwave Oven",
    "SEMI AUTOMATIC [WM01]": "Washing Machine",
    "SID BY SIDE REF [REFSBS584]": "Refrigerator",
    "SOLOMWO [SOLO]": "Microwave Oven",
    "STAB [STABILIZER]": "Stabilizer",
    "UNDER CEILING - CONSOLE TYPE [UC]": "Under Ceiling AC",
    "VRF [VRF001]": "VRF",
    "WATER DISPENSER [MWD]": "Water Dispenser",
    "WATER HEATER INSTANT [WH01]": "Water Heater",
    "WATER HEATER STORAGE ABS [SA]": "Water Heater",
    "WATER HEATER STORAGE METAL [SM]": "Water Heater",
    "WATER PURIFIER [WP01]": "Water Purifier",
    "WINDOW [WINDOW]": "Window AC",
    "WINDOW ROOM AIR CONDITIONER [WRAC]": "Window AC",
    "WINDOW ROOM AIR CONDITIONER INVERTER [WRACIV]": "Window AC",
    "WINE COOLERS DOUBLE DOOR [WCDD]": "Wine Cooler",
    "WINE COOLERS SINGLE DOOR [WCSD]": "Wine Cooler",
    "AIR PURIFIER FLOOR STANDING MI [FSMI]": "Air Purifier",
    "AIR PURIFIER TABLE TOP MI [APTTMI]": "Air Purifier",
    "CHIMNEY 60 CM [CHM001]": "Chimney",
    "CHIMNEY 90 CM [CHM002]": "Chimney",
    "CONVECTION MICRO WAVE OVEN MI [MWO04]": "Microwave Oven",
    "DISH WASHER COUNTER TOP MI [CTMI]": "Dish Washer",
    "DISH WASHER FLOOR STANDING MI [DWFSMI]": "Dish Washer",
    "FRONT LOADING MI [WM03MI]": "Washing Machine",
    "FULLY AUTOMATIC TOP LOADING MI [WM02MI]": "Washing Machine",
    "GRILL MICRO WAVE OVEN MI [MWO03]": "Microwave Oven",
    "INDUCTION COOK TOP 001 [INDUCTION001]": "Induction Cook Top",
    "OVEN TOSTER GRILL 01 [OTG-1]": "Oven Toaster Grill",
    "REFDIRECTCOOL [REFDC]": "Refrigerator",
    "REF FROST FREE MI [REFFFMI]": "Refrigerator",
    "REF MULTI DOOR MI [REFMLDMI]": "Refrigerator",
    "REF Side by Side MI [REFSBSMI]": "Refrigerator",
    "ROTISSERRIE MICRO WAVE OVEN MI [MWO01]": "Microwave Oven",
    "SEMI AUTOMATIC MI [WM01MI]": "Washing Machine",
    "SOLO MICRO WAVE OVEN MI [MWO02]": "Microwave Oven",
    "VACCUM CLEANER 002 [VCL002]": "Vacuum Cleaner",
    "VACCUM CLEANER WIRED [VCL001]": "Vacuum Cleaner",
    "VACCUM CLEANER WIRELESS [VCL003]": "Vacuum Cleaner",
    "WATER DISPENSERR MI [MWD01MI]": "Water Dispenser",
    "WATER HEATER INSTANT MI [WH01MI]": "Water Heater",
    "WATER HEATER STORAGE ABS MI [WH03MI]": "Water Heater",
    "WATER HEATER STORAGE METAL MI [WH02MI]": "Water Heater",
    "WATER PURIFIER MI [WP01MI]": "Water Purifier",
    "WINE COOLERS DOUBLE DOOR MI [WCDDMI]": "Wine Cooler",
    "Premium AC": "AC",
    "Air Conditioner": "AC",
    "Commercial Refrigeration": "Deep Freezer",
    "Room Air": "AC",
    "Sky Air": "Cassette AC",
};

export const UnitStatusMap = {
    "Under Warranty": "Warranty",
    Warranty: "Warranty",
    AMC: "AMC",
    "Special Warranty": "Warranty",
    "Out of Warranty": "Out Of Warranty",
    "Out Of Warranty": "Out Of Warranty",
    "Out of Coverage": "Out Of Warranty",
    "Out Of Coverage": "Out Of Warranty",
    SC: "Warranty",
    NA: "Out Of Warranty",
    "In Warranty": "Warranty",
    "Compressor Warranty": "Out Of Warranty",
};

export const BrandMap = {
    "CARRIER MIDEA INDIA PVT LTD [CMI]": "Carrier",
    "MIDEA INDIA PVT LTD [MI]": "Midea",
    Voltas: "Voltas",
};

export const CallTypeMap = {
    "Preventive Maintenance": "Service",
    "Installation/Demo": "Installation",
    Breakdown: "Not Cooling/Working",
    RMS: "Service",
};
